# Generated by Django 5.0.1 on 2024-12-14 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ReservasApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='observacion',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
